WebApplication1/Models/Applicant.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.Web.UI.HtmlControls;

    public partial class Applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant()
        {
            this.ApplicantExes = new List<ApplicantEx>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime DOB { get; set; }
        public string PicPath { get; set; }
        public bool IsAvailable { get; set; }
        public int TotalEx { get; set; }
        [NotMapped]
        public HttpPostedFileBase Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<ApplicantEx> ApplicantExes { get; set; }
    }
}

WebApplication1/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace Master_Detail.Controllers
{
    public class ApplicantController : Controller
    {
        readonly Retac_Master_DEntities db = new Retac_Master_DEntities();
        // GET: Applicant
        public ActionResult Index()
        {
            return View(db.Applicants.ToList());
        }
        public ActionResult Create()
        {
            Applicant applicant = new Applicant();
            applicant.ApplicantExes.Add(new ApplicantEx
            {
                CompanyName = "",
                Designation = "",
                YearOfEx = 0
            });

            return View(applicant);
        }
        [HttpPost]
        public ActionResult Create(Applicant applicant, string btn)
        {
            if (btn == "Add")
            {
                applicant.ApplicantExes.Add(new ApplicantEx());
            }
            if (btn == "Create")
            {
                if (applicant.Picture != null)
                {
                    string ext = Path.GetExtension(applicant.Picture.FileName);
                    if (ext == ".jpg" || ext == ".png")
                    {
                        string rootpath = Server.MapPath("~/");
                        string fileTosave = Path.Combine(rootpath, "Pictures", applicant.Picture.FileName);
                        applicant.Picture.SaveAs(fileTosave);
                        applicant.PicPath = "~/Pictures/" + applicant.Picture.FileName;

                        applicant.TotalEx = applicant.ApplicantExes.Sum(s => s.YearOfEx);
                        db.Applicants.Add(applicant);
                        if (db.SaveChanges() > 0)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Please provide valid Image");
                        return View(applicant);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Please provide valid Image");
                    return View(applicant);
                }
            }
            return View(applicant);
        }

        public ActionResult Edit(int id)
        {
            Applicant applicant = db.Applicants.Find(id);


            return View(applicant);
        }
        [HttpPost]
        public ActionResult Edit(Applicant applicant, string btn)
        {
            var updateApp = db.Applicants.Find(applicant.Id);
            if (btn == "Add")
            {
                updateApp.ApplicantExes.Add(new ApplicantEx());
            }
            if (btn == "Update")
            {

                if (applicant.Picture != null)
                {
                    string ext = Path.GetExtension(applicant.Picture.FileName);
                    if (ext == ".jpg" || ext == ".png")
                    {
                        string rootpath = Server.MapPath("~/");
                        string fileTosave = Path.Combine(rootpath, "Pictures", applicant.Picture.FileName);
                        applicant.Picture.SaveAs(fileTosave);
                        updateApp.PicPath = "~/Pictures/" + applicant.Picture.FileName;
                    }
                    else
                    {
                        ModelState.AddModelError("", "Please provide valid Image");
                        return View(applicant);
                    }
                }
                else
                {
                    updateApp.PicPath = applicant.PicPath;
                }

                updateApp.DOB = applicant.DOB;
                updateApp.Id = applicant.Id;
                updateApp.Name = applicant.Name;
                updateApp.IsAvailable = applicant.IsAvailable;

                db.ApplicantExes.RemoveRange(db.ApplicantExes.Where(a => a.AppId.Equals(updateApp.Id)));
                db.SaveChanges();
                updateApp.ApplicantExes = applicant.ApplicantExes;
                updateApp.TotalEx = applicant.ApplicantExes.Sum(s => s.YearOfEx);
                db.Entry(updateApp).State = System.Data.Entity.EntityState.Modified;

                if (db.SaveChanges() > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(updateApp);
        }
        public ActionResult Delete(int id)
        {
            db.Applicants.Remove(db.Applicants.Find(id));

            db.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

WebApplication1/Views/Applicant/Create.cshtml
@model WebApplication1.Models.Applicant

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Applicant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Applicant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.PicPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <input type="file" name="Picture" />
                @Html.ValidationMessageFor(model => model.PicPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.IsAvailable)
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-success float-end" name="btn" formnovalidate />
            </div>
        </div>
        <div class="form-group">
            <table class="table table-bordered">
                <tr>
                    <td>Company</td>
                    <td>Designation</td>
                    <td>Year of Experience</td>
                </tr>
                @for (int i = 0; i < Model.ApplicantExes.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.EditorFor(m => Model.ApplicantExes[i].CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => Model.ApplicantExes[i].CompanyName)
                        </td>
                        <td>
                            @Html.EditorFor(m => Model.ApplicantExes[i].Designation, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => Model.ApplicantExes[i].Designation)
                        </td>
                        <td>
                            @Html.EditorFor(m => Model.ApplicantExes[i].YearOfEx, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => Model.ApplicantExes[i].YearOfEx)
                        </td>
                        <td>
                            <input type="submit" value="Remove" onclick="Remove(this)" class="btn btn-danger" />
                        </td>
                    </tr>
                }
            </table>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" name="btn" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function Remove(e) {
            $(e).closest('tr').remove();
        }
    </script>
}

WebApplication1/Views/Applicant/Edit.cshtml
@model WebApplication1.Models.Applicant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Applicant Info</h2>


@using (Html.BeginForm("Edit", "Applicant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(m => m.Id)
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.PicPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(m => m.PicPath)
                <input type="file" name="Picture" />
                @Html.ValidationMessageFor(model => model.PicPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.IsAvailable)
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-success float-end" name="btn" formnovalidate />
            </div>
        </div>
        <div class="form-group">
            <table class="table table-bordered">
                <tr>
                    <td>Company</td>
                    <td>Designation</td>
                    <td>Year of Experience</td>
                </tr>
                @for (int i = 0; i < Model.ApplicantExes.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(m => Model.ApplicantExes[i].AppId)
                            @Html.EditorFor(m => Model.ApplicantExes[i].CompanyName, new { htmlAttributes = new { @class = "form-control" } })

                            @Html.ValidationMessageFor(m => Model.ApplicantExes[i].CompanyName)
                        </td>
                        <td>
                            @Html.EditorFor(m => Model.ApplicantExes[i].Designation, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => Model.ApplicantExes[i].Designation)
                        </td>
                        <td>
                            @Html.EditorFor(m => Model.ApplicantExes[i].YearOfEx, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => Model.ApplicantExes[i].YearOfEx)
                        </td>
                        <td>
                            <input type="submit" value="Remove" onclick="Remove(this)" class="btn btn-danger" />
                        </td>
                    </tr>
                }
            </table>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" name="btn" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function Remove(e) {
            $(e).closest('tr').remove();
        }
    </script>
}

WebApplication1/Views/Applicant/Index.cshtml
@model IEnumerable<WebApplication1.Models.Applicant>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PicPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalEx)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DOB)
        </td>
        <td>
            
            <img src="@Url.Content(item.PicPath)" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAvailable)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalEx)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>